<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <Nullable>enable</Nullable>
        <RootNamespace>HelloWorld.Cfn</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.Core" Version="2.5.0" />
        <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.4" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\src\HelloWorld\HelloWorld.csproj" />
    </ItemGroup>
</Project>
