using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class UASourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => 
        {
            var source = @"// <auto-generated />
using System.Runtime.CompilerServices;
using AWS.Lambda.Powertools.Common;

namespace PowertoolsGenerated
{
    internal static class UAModuleInitializerKafkaProtobuf
    {
        [ModuleInitializer]
        internal static void Initialize()
        {
            PowertoolsEnvironment.Instance.SetExecutionEnvironment(typeof(AWS.Lambda.Powertools.Kafka.Protobuf.PowertoolsKafkaProtobufSerializer), ""Kafka.Protobuf"");
        }
    }
}";
            ctx.AddSource("UAModuleInitializerKafkaProtobuf.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }
}
