<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>default</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>AWS.Lambda.Powertools.ConcurrencyTests</AssemblyName>
        <RootNamespace>AWS.Lambda.Powertools.ConcurrencyTests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <!--   Package versions are Centrally managed in Directory.Packages.props file  -->
        <!--   More info https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management   -->
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Amazon.Lambda.TestUtilities" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\AWS.Lambda.Powertools.BatchProcessing\AWS.Lambda.Powertools.BatchProcessing.csproj" />
        <ProjectReference Include="..\..\src\AWS.Lambda.Powertools.Idempotency\AWS.Lambda.Powertools.Idempotency.csproj" />
        <ProjectReference Include="..\..\src\AWS.Lambda.Powertools.Logging\AWS.Lambda.Powertools.Logging.csproj" />
        <ProjectReference Include="..\..\src\AWS.Lambda.Powertools.Metrics\AWS.Lambda.Powertools.Metrics.csproj" />
        <ProjectReference Include="..\..\src\AWS.Lambda.Powertools.Parameters\AWS.Lambda.Powertools.Parameters.csproj" />
        <ProjectReference Include="..\..\src\AWS.Lambda.Powertools.Tracing\AWS.Lambda.Powertools.Tracing.csproj" />
    </ItemGroup>

</Project>
