<!--suppress MsbuildTargetFrameworkTagInspection -->
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>AWS.Lambda.Powertools.SourceGenerator.Tests</AssemblyName>
        <RootNamespace>AWS.Lambda.Powertools.SourceGenerator.Tests</RootNamespace>
        <TargetFrameworks>net8.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio">
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\AWS.Lambda.Powertools.BatchProcessing\AWS.Lambda.Powertools.BatchProcessing.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true"/>
        <ProjectReference Include="..\..\src\AWS.Lambda.Powertools.EventHandler.Resolvers.BedrockAgentFunction\AWS.Lambda.Powertools.EventHandler.Resolvers.BedrockAgentFunction.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true"/>
        <ProjectReference Include="..\..\src\AWS.Lambda.Powertools.EventHandler\AWS.Lambda.Powertools.EventHandler.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true"/>
        <ProjectReference Include="..\..\src\AWS.Lambda.Powertools.Idempotency\AWS.Lambda.Powertools.Idempotency.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true"/>
        <ProjectReference Include="..\..\src\AWS.Lambda.Powertools.Kafka.Avro\AWS.Lambda.Powertools.Kafka.Avro.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true"/>
        <ProjectReference Include="..\..\src\AWS.Lambda.Powertools.Kafka.Json\AWS.Lambda.Powertools.Kafka.Json.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true"/>
        <ProjectReference Include="..\..\src\AWS.Lambda.Powertools.Kafka.Protobuf\AWS.Lambda.Powertools.Kafka.Protobuf.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true"/>
        <ProjectReference Include="..\..\src\AWS.Lambda.Powertools.Logging\AWS.Lambda.Powertools.Logging.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true"/>
        <ProjectReference Include="..\..\src\AWS.Lambda.Powertools.Metrics\AWS.Lambda.Powertools.Metrics.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true"/>
        <ProjectReference Include="..\..\src\AWS.Lambda.Powertools.Parameters\AWS.Lambda.Powertools.Parameters.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true"/>
        <ProjectReference Include="..\..\src\AWS.Lambda.Powertools.Tracing\AWS.Lambda.Powertools.Tracing.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true"/>
    </ItemGroup>

</Project>
