// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AWS.Lambda.Powertools.Kafka.Tests
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class AvroKey : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""AvroKey"",""namespace"":""AWS.Lambda.Powertools.Kafka.Tests"",""fields"":[{""name"":""id"",""type"":""int""},{""name"":""color"",""type"":{""type"":""enum"",""name"":""Color"",""namespace"":""AWS.Lambda.Powertools.Kafka.Tests"",""symbols"":[""UNKNOWN"",""GREEN"",""RED""],""default"":""UNKNOWN""}}]}");
		private int _id;
		private AWS.Lambda.Powertools.Kafka.Tests.Color _color = AWS.Lambda.Powertools.Kafka.Tests.Color.UNKNOWN;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return AvroKey._SCHEMA;
			}
		}
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public AWS.Lambda.Powertools.Kafka.Tests.Color color
		{
			get
			{
				return this._color;
			}
			set
			{
				this._color = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.color;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.Int32)fieldValue; break;
			case 1: this.color = (AWS.Lambda.Powertools.Kafka.Tests.Color)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
