<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.Core" Version="2.8.0" />
        <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="2.7.3" />
        <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.4" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\..\libraries\src\AWS.Lambda.Powertools.Idempotency\AWS.Lambda.Powertools.Idempotency.csproj" />
        <ProjectReference Include="..\..\..\..\libraries\src\AWS.Lambda.Powertools.Logging\AWS.Lambda.Powertools.Logging.csproj" />
    </ItemGroup>
</Project>
