name: Maintenance
description: Suggest an activity to help address tech debt, governance, and anything internal
title: "Maintenance: TITLE"
labels: ["internal", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to help us improve operational excellence.

        *Future readers*: Please react with 👍 and your use case to help us understand customer demand.
  - type: textarea
    id: activity
    attributes:
      label: Summary
      description: Please provide an overview in one or two paragraphs
    validations:
      required: true
  - type: textarea
    id: importance
    attributes:
      label: Why is this needed?
      description: Please help us understand the value so we can prioritize it accordingly
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Which area does this relate to?
      multiple: true
      options:
        - Automation
        - Governance
        - .NET SDK
        - Tests
        - Tracing
        - Logging
        - Metrics
        - Parameters
        - Idempotency
        - Batch Processing
        - Feature flags
        - Other
  - type: textarea
    id: suggestion
    attributes:
      label: Solution
      description: If available, please share what a good solution would look like
    validations:
      required: false
  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Acknowledgment
      options:
        - label: This request meets [Powertools for AWS Lambda (.NET) Tenets](https://docs.powertools.aws.dev/lambda/dotnet/#tenets)
          required: true
  - type: markdown
    attributes:
      value: |
        ---

        **Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.
