<!--suppress MsbuildTargetFrameworkTagInspection -->
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>AWS.Lambda.Powertools.Kafka</PackageId>
        <Description>Powertools for AWS Lambda (.NET) - Kafka consumer package.</Description>
        <AssemblyName>AWS.Lambda.Powertools.Kafka</AssemblyName>
        <RootNamespace>AWS.Lambda.Powertools.Kafka</RootNamespace>
        <TargetFrameworks>net8.0</TargetFrameworks>
        <TargetMultiFramework>false</TargetMultiFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Amazon.Lambda.Core" />
      <PackageReference Include="Apache.Avro" />
    </ItemGroup>

</Project>
