<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <AWSProjectType>Lambda</AWSProjectType>
        <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <!-- Generate ready to run images during publishing to improve cold start time. -->
         <PublishReadyToRun>true</PublishReadyToRun>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.RuntimeSupport" Version="1.12.0" />
        <PackageReference Include="Amazon.Lambda.Core" Version="2.5.0" />
        <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.4" />
        <PackageReference Include="AWS.Lambda.Powertools.Logging" Version="2.0.0" />
        <PackageReference Include="AWS.Lambda.Powertools.Kafka.Protobuf" Version="1.0.2" />
        <PackageReference Include="Grpc.Tools" Version="2.72.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
      <Content Update="kafka-protobuf-event.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
    <ItemGroup>
        <Protobuf Include="CustomerProfile.proto">
            <GrpcServices>Client</GrpcServices>
            <Access>Public</Access>
            <ProtoCompile>True</ProtoCompile>

            <CompileOutputs>True</CompileOutputs>
            <OutputDir>obj\Debug/net8.0/</OutputDir>
            <Generator>MSBuild:Compile</Generator>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Protobuf>
    </ItemGroup>
</Project>