<!--suppress MsbuildTargetFrameworkTagInspection -->
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <!--  Remaining properties are defined in Directory.Build.props  -->
        <PackageId>AWS.Lambda.Powertools.EventHandler.Resolvers.BedrockAgentFunction.AspNetCore</PackageId>
        <Description>Powertools for AWS Lambda (.NET) - Event Handler Bedrock Agent Function Resolver AspNetCore package.</Description>
        <AssemblyName>AWS.Lambda.Powertools.EventHandler.Resolvers.BedrockAgentFunction.AspNetCore</AssemblyName>
        <RootNamespace>AWS.Lambda.Powertools.EventHandler.Resolvers.BedrockAgentFunction.AspNetCore</RootNamespace>
        <TargetFrameworks>net8.0</TargetFrameworks>
        <TargetMultiFramework>false</TargetMultiFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Http" />
        <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    </ItemGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\AWS.Lambda.Powertools.EventHandler.Resolvers.BedrockAgentFunction\AWS.Lambda.Powertools.EventHandler.Resolvers.BedrockAgentFunction.csproj" />
    </ItemGroup>

</Project>
