AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kafka

  Sample SAM Template for kafka

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
    MemorySize: 512
    Runtime: dotnet10

Resources:
  AvroDeserializationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Avro.Example
      Architectures:
        - x86_64
      Tracing: Active
      Environment: # Powertools env vars: https://awslabs.github.io/aws-lambda-powertools-python/#environment-variables
        Variables:
          POWERTOOLS_SERVICE_NAME: PowertoolsHelloWorld
          POWERTOOLS_LOG_LEVEL: Info
          POWERTOOLS_LOGGER_CASE: PascalCase # Allowed values are: CamelCase, PascalCase and SnakeCase (Default)