<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.Core" Version="2.8.0" />
        <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="2.7.3" />
        <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.4" />
        <PackageReference Include="AWS.Lambda.Powertools.Parameters" Version="3.0.2" />
    </ItemGroup>
</Project>
