using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace AWS.Lambda.Powertools.EventHandler.Resolvers.BedrockAgentFunction.SourceGenerators;

/// <summary>
/// Source generator that automatically sets the AWS_SDK_UA_APP_ID environment variable
/// </summary>
[Generator]
public class UASourceGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Initializes the source generator.
    /// </summary>
    /// <param name="context"></param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register the compilation provider to ensure we run during compilation
        var compilationProvider = context.CompilationProvider;
        
        context.RegisterSourceOutput(compilationProvider, (ctx, compilation) => 
        {
            var source = """
                         // <auto-generated />
                         using System.Runtime.CompilerServices;

                         namespace AWS.Lambda.Powertools.EventHandler.Resolvers.BedrockAgentFunction.Internal
                         {
                             internal static class UAModuleInitializer
                             {
                                 [ModuleInitializer]
                                 internal static void Initialize()
                                 {
                                     EnvWrapper.SetExecutionEnvironment();
                                 }
                             }
                         }
                         """;
            ctx.AddSource("UAModuleInitializer.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }
}

