using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

/// <summary>
/// Source generator that automatically sets the AWS_SDK_UA_APP_ID environment variable
/// </summary>
[Generator]
public class UASourceGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Initializes the source generator.
    /// </summary>
    /// <param name="context"></param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => 
        {
            var source = @"// <auto-generated />
using System.Runtime.CompilerServices;
using AWS.Lambda.Powertools.Common;

namespace PowertoolsGenerated
{
    internal static class UAModuleInitializerBedrockAgentFunctionResolver
    {
        [ModuleInitializer]
        internal static void Initialize()
        {
            PowertoolsEnvironment.Instance.SetExecutionEnvironment(typeof(AWS.Lambda.Powertools.EventHandler.Resolvers.BedrockAgentFunctionResolver));
        }
    }
}";
            ctx.AddSource("UAModuleInitializerBedrockAgentFunctionResolver.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }
}

