<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AWSProjectType>Lambda</AWSProjectType>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <PublishAot>true</PublishAot>
        <StripSymbols>true</StripSymbols>
        <TrimMode>partial</TrimMode>
        <RootNamespace>AOT_FunctionSQS</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.RuntimeSupport" Version="1.12.0"/>
        <PackageReference Include="Amazon.Lambda.Core" Version="2.5.0"/>
        <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.4"/>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\..\..\..\..\..\src\AWS.Lambda.Powertools.BatchProcessing\AWS.Lambda.Powertools.BatchProcessing.csproj" />
    </ItemGroup>
</Project>