<!--suppress MsbuildTargetFrameworkTagInspection -->
<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="../KafkaDependencies.props" />
    <PropertyGroup>
        <PackageId>AWS.Lambda.Powertools.Kafka.Protobuf</PackageId>
        <Description>Powertools for AWS Lambda (.NET) - Kafka Protobuf consumer package.</Description>
        <AssemblyName>AWS.Lambda.Powertools.Kafka.Protobuf</AssemblyName>
        <RootNamespace>AWS.Lambda.Powertools.Kafka.Protobuf</RootNamespace>
        <TargetFrameworks>net8.0</TargetFrameworks>
        <TargetMultiFramework>false</TargetMultiFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IncludeExecutionEnvironment>true</IncludeExecutionEnvironment>
    </PropertyGroup>

    <!-- Release: Use source file inclusion -->
    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <IncludeKafkaFiles>true</IncludeKafkaFiles>
        <DefineConstants>$(DefineConstants);KAFKA_PROTOBUF</DefineConstants>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Google.Protobuf" />
        <PackageReference Include="Microsoft.CodeAnalysis.Common" />
    </ItemGroup>

    <!-- Debug: Use project references -->
    <ItemGroup Condition="'$(Configuration)'=='Debug'">
        <ProjectReference Include="..\AWS.Lambda.Powertools.Kafka\AWS.Lambda.Powertools.Kafka.csproj"/>
        <ProjectReference Include="..\AWS.Lambda.Powertools.Common\AWS.Lambda.Powertools.Common.csproj"/>
    </ItemGroup>
    
</Project>
