name: Build .NET

on:
  push:
    paths:
      - "libraries/**"
    branches: [develop]
  pull_request:
    paths:
      - "libraries/**"
    branches: [develop]

permissions: {}

defaults:
  run:
    working-directory: ./libraries

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # 5.4.0
        with:
          dotnet-version: |
            8.0.x
            10.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore /tl

      - name: Test & Code Coverage
        run: dotnet test --no-restore --filter "Category!=E2E" --collect:"XPlat Code Coverage" --results-directory ./codecov

      - name: Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # 7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          name: codecov-lambda-powertools-dotnet
          verbose: true
          directory: ./libraries/codecov
