name: Build .NET

on:
  push:
    paths:
      - "libraries/**"
    branches: [develop]
  pull_request:
    paths:
      - "libraries/**"
    branches: [develop]

permissions: {}

defaults:
  run:
    working-directory: ./libraries

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # 5.4.0
        with:
          dotnet-version: |
            8.0.x
            10.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore /tl

      - name: Test & Code Coverage
        run: dotnet test --no-restore --filter "Category!=E2E" --collect:"XPlat Code Coverage" --results-directory ./codecov

      - name: Codecov
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # 6.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          name: codecov-lambda-powertools-dotnet
          verbose: true
          directory: ./libraries/codecov
