# Standalone workflow to update changelog if necessary
name: Build changelog

on:
  workflow_dispatch:

jobs:
  changelog:
    permissions:
      contents: write       # create temporary branch to store changelog changes
      pull-requests: write  # create PR with changelog changes
    uses: ./.github/workflows/reusable_publish_changelog.yml
