# Standalone workflow to update changelog if necessary
name: Build changelog

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  changelog:
    uses: ./.github/workflows/reusable_publish_changelog.yml
