name: Build .NET

on:
  push:
    paths:
      - "libraries/**"
    branches: [develop]
  pull_request:
    paths:
      - "libraries/**"
    branches: [develop]

defaults:
  run:
    working-directory: ./libraries

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # 5.0.1
        with:
          dotnet-version: |
            8.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore /tl

      - name: Test & Code Coverage
        run: dotnet test --no-restore --filter "Category!=E2E" --collect:"XPlat Code Coverage" --results-directory ./codecov --verbosity normal

      - name: Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # 5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          name: codecov-lambda-powertools-dotnet
          verbose: true
          directory: ./libraries/codecov
