name: Examples Tests

on:
  push:
    paths:
      - "examples/**"
    branches: [develop]
  pull_request:
    paths:
      - "examples/**"
    branches: [develop]

permissions: {}

defaults:
  run:
    working-directory: ./examples

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # 5.2.0
        with:
          dotnet-version: |
            8.0.x
            10.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Install global tools
        run: dotnet tool install --global Apache.Avro.Tools

      - name: Build
        run: dotnet build --configuration Release --no-restore /tl

      - name: Test Examples
        run: dotnet test --no-restore --verbosity normal
