name: Examples Tests

on:
  push:
    paths:
      - "examples/**"
    branches: [develop]
  pull_request:
    paths:
      - "examples/**"
    branches: [develop]

defaults:
  run:
    working-directory: ./examples

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0.0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # 5.0.1
        with:
          dotnet-version: |
            8.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Install global tools
        run: dotnet tool install --global Apache.Avro.Tools

      - name: Build
        run: dotnet build --configuration Release --no-restore /tl

      - name: Test Examples
        run: dotnet test --no-restore --verbosity normal
