name: Record PR details

on:
  pull_request:
    types: [opened, edited, closed]


permissions: {}
  
jobs:
  record_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: "Extract PR details"
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const script = require('.github/scripts/save_pr_details.js')
            await script({github, context, core})
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: pr
          path: pr.txt
