name: Record PR details

on:
  pull_request:
    types: [opened, edited, closed]


permissions: {}
  
jobs:
  record_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: "Extract PR details"
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const script = require('.github/scripts/save_pr_details.js')
            await script({github, context, core})
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: pr
          path: pr.txt
