name: Release Drafter

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions: {}

jobs:
  update_release_draft:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@693d20e7c1ce1a81d3a41962f85914253b518449 # v5.20.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
