name: Lockdown untrusted workflows

on:
  push:
    paths:
      - ".github/workflows/**"
  pull_request:
    paths:
      - ".github/workflows/**"

permissions: {}

jobs:
  enforce_pinned_workflows:
    name: Harden Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Ensure 3rd party workflows have SHA pinned
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@471d5ace1f08e3c4df1c4c2f7e6341aa75da434a # v5.0.3
        with:
          # Trusted GitHub Actions and/or organizations
          allowlist: |
            aws-actions/
            actions/checkout
            actions/github-script
            actions/setup-dotnet
            actions/setup-python
            actions/upload-artifact
            actions/download-artifact
            github/codeql-action/init
            github/codeql-action/analyze
            dependabot/fetch-metadata
